### ISSUE TITLE
Graphic rendering in Qlik Sense Browser

### ISSUE THREAD

**Issue by RitaAguiar** [rileymd88/qwik-trellis#2]
Hi rileymd88
Your extension has been very helpful! However, sometimes there's an issue when rendering the graphics, even when using Qlik Sense in the browser. As you can see, the first image shows the graphic correctly rendered and the second image shows the graphic after changing the visualization to another sheet and coming back to it.

![qlik sense 59](https://user-images.githubusercontent.com/44228423/53240298-4315b080-3696-11e9-913d-9b850c4b84cc.png)
![qlik sense 60](https://user-images.githubusercontent.com/44228423/53240299-4315b080-3696-11e9-8e56-aff8acc98572.png)

It would be awesome if you could also get this extension to render in the Qlik Sense Desktop as well.

P.S.: I would also like to suggest an option to merge all graphics in one and represent the 3rd dimension either stacked or with more columns. That would be great.

Thank you

**Comment by rileymd88** [comment]
Hi @RitaAguiar 

I am not sure what the issue is exactly. I have also released a new version which fixes the Qlik Sense Desktop issue. I believe this extension can also help meet your requirement if you changed your master viz to a stacked bar chart instead of grouped (found in Appearance -> Presentation in the master viz settings) and then you can change the column number in the extension (found in Options -> Qwik Trellis Options -> Number of Columns) and then change the column number to 1 and refresh your browser or Qlik Sense Desktop Client.
